In [5]:
import numpy as np

A = np.eye(2)
B = np.array( [ [10],
                [20] ])

In [6]:
A

array([[1., 0.],
       [0., 1.]])

In [7]:
B

array([[10],
       [20]])

In [8]:
A.shape

(2, 2)

In [9]:
B.shape

(2, 1)

In [10]:
np.matmul(A,B)

array([[10.],
       [20.]])

In [11]:
A @ B

array([[10.],
       [20.]])

In [12]:
help( np.multiply )

Help on ufunc:

multiply = <ufunc 'multiply'>
    multiply(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Multiply arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        Input arrays to be multiplied.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere,

In [14]:
5 * np.eye(3) * np.eye(3)

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])